version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: project1_db
      POSTGRES_USER: project1_user
      POSTGRES_PASSWORD: Qwer-1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=Shop.settings

volumes:
  postgres_data: